[package]
name = "uuidutil"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.13", features = ["derive"] }

[dependencies.uuid]
version = "1.10.0"
features = ["v4", "v7"]

[profile.release]
opt-level = 3
